apiVersion: v1
kind: Pod
metadata:
   name: {{ .Release.Name }}-cpu-pod-1
spec:
  containers:
  - name: {{ .Release.Name }}-cpu-pin-pod
    image: {{ .Values.image }}
    command:
    - /sbin/init
    resources:
      limits:
        memory: "200Mi"
        cpu: "{{ .Values.cpucount}}"
      requests:
        memory: "200Mi"
        cpu: "{{ .Values.cpucount}}"

