apiVersion: v1
kind: Pod
metadata:
   name: {{ .Release.Name }}-cpu-pod-1
spec:
  containers:
  - name: {{ .Release.Name }}-cpu-pin-pod
    image: {{ .Values.image }}
    command:
    - /sbin/init
    resources:
      limits:
        memory: "200Mi"
        {{- if .Values.windriverisolcpus }}
        windriver.com/isolcpus: "{{ .Values.cpucount }}"
        {{- else }}
        cpu: "{{ .Values.cpucount}}"
        {{- end }}

      requests:
        memory: "200Mi"
        {{- if .Values.windriverisolcpus }}
        windriver.com/isolcpus: "{{ .Values.cpucount }}"
        {{- else }}
        cpu: "{{ .Values.cpucount}}"
        {{- end }}

