apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Release.Name }}-dpdk-network
  annotations:
    k8s.v1.cni.cncf.io/resourceName: {{ .Values.NetworkResourceName }}
spec:
  config: '{
   "cniVersion": "0.3.0",
   {{- if .Values.vlan }}
   "vlan": {{ .Values.vlan }},
   {{- end }}
   "type": "sriov"
}'
