apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-dpdkapp-testpmd
  annotations:
     k8s.v1.cni.cncf.io/networks: '[
        { "name": "{{ .Release.Name }}-dpdk-network" },
        { "name": "{{ .Release.Name }}-dpdk-network" }
     ]'
spec:
   restartPolicy: Never
   containers:
   - name: {{ .Release.Name }}-dpdkapp-testpmd
     image: {{ .Values.image }}
     volumeMounts:
     - mountPath: /mnt/huge-1048576kB
       name: {{ .Release.Name }}-hugepage
     stdin: true
     tty: true
     securityContext:
        privileged: true
        allowPrivilegeEscalation: true
        capabilities:
          add: ["IPC_LOCK", "NET_ADMIN", "NET_RAW"]
     resources:
       requests:
         memory: 1Gi
         hugepages-1Gi: 8Gi
         {{ .Values.NetworkResourceName }}: '2'
         {{- if .Values.windriverisolcpus }}
         windriver.com/isolcpus: 3
         {{- else }}
         cpu: 3
         {{- end }}
       limits:
         hugepages-1Gi: 8Gi
         memory: 1Gi
         {{ .Values.NetworkResourceName }}: '2'
         {{- if .Values.windriverisolcpus }}
         windriver.com/isolcpus: 3
         {{- else }}
         cpu: 3
         {{- end }}
   volumes:
    - name: {{ .Release.Name }}-hugepage
      emptyDir:
        medium: HugePages

