apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-multi-net-pod-01
  annotations:
    k8s.v1.cni.cncf.io/networks: {{ .Release.Name }}-macvlan-net0
spec:
  containers:
  - name: {{ .Release.Name }}-multi-net-pod-01
    image: {{ .Values.image }}
    command:
    - /sbin/init

---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-multi-net-pod-02
  annotations:
    k8s.v1.cni.cncf.io/networks: {{ .Release.Name }}-macvlan-net0
spec:
  containers:
  - name: {{ .Release.Name }}-multi-net-pod-02
    image: {{ .Values.image }}
    command:
    - /sbin/init

