apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Release.Name }}-macvlan-net0
spec:
  config: '{
   "cniVersion": "0.3.1",
   "type": "macvlan",
   "master": "{{ .Values.macvlanintf }}",
   "mode": "bridge",
   "ipam": {
      "type": "host-local",
      "subnet": "{{ .Values.subnet }}",
      "rangeStart": "{{ .Values.startip }}",
      "rangeEnd": "{{ .Values.endip }}",
      "routes": [{
          "dst": "0.0.0.0/0", "gw": "{{ .Values.gateway }}"
        }],
      "gateway": "{{ .Values.gateway }}"
    }
}'
