FROM ubuntu:latest

RUN apt update -y 

RUN apt install -y vim

RUN apt install -y net-tools

RUN apt install -y iproute2

RUN apt install -y tcpdump

RUN apt install -y iputils-ping

RUN apt install -y curl

RUN apt install -y nginx

CMD ["sleep", "infinity"]
