apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Release.Name }}-sriov-network
  annotations:
    k8s.v1.cni.cncf.io/resourceName: {{ .Values.NetworkResourceName }}
spec:
  config: '{
   "cniVersion": "0.3.0",
   "type": "sriov",
   {{- if .Values.vlan }}
   "vlan": {{ .Values.vlan }},
   {{- end }}
   "ipam": {
      "type": "host-local",
      "subnet": "{{ .Values.subnet }}",
      "rangeStart": "{{ .Values.startip }}",
      "rangeEnd": "{{ .Values.endip }}",
      "routes": [{
          "dst": "0.0.0.0/0", "gw": "{{ .Values.gateway }}"
        }],
      "gateway": "{{ .Values.gateway }}"
    }
}'
