apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
   name: {{ .Release.Name }}-db-np
   labels:
     day: day3
     sample: homework
     chart: {{ .Chart.Name }}
     release: {{ .Release.Name }}
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels:
       day: day3
       sample: dbapp
       layer: backend 
       chart: {{ .Chart.Name }}
       release: {{ .Release.Name }}
  ingress:
  - from:
     - podSelector:
         matchLabels:
           day: day3
           sample: dbapp
           layer: frontend
           chart: {{ .Chart.Name }}
           release: {{ .Release.Name }}
    ports:
    - port: 3306
