sriovapp:
  enabled: false
  NetworkResourceName: intel.com/sriov_netdevice
  # if vlan is not required. keep value empty
  vlan: 100
  subnet: 192.168.100.0/24
  startip: 192.168.100.10
  endip: 192.168.100.50
  gateway: 192.168.100.1

dpdkapp:
  enabled: false
  NetworkResourceName: intel.com/dpdk_netdevice
  image: quay.io/cgrepo/dpdk-apps:21.02

cpupinapp:
  enabled: false
  cpucount: 1

hugepageapp:
  enabled: false
  cpucount: 1
  hugepages: 1Gi

dbapp:
  enabled: false
  nodePort: 31000
  dbPassword: something
  storageClass: vsphere-sc
  fereplicas: 1

multinetapp:
  enabled: false
  subnet: 192.167.7.0/24
  startip: 192.167.7.20
  endip: 192.167.7.100
  gateway: 192.167.7.1
