sriovapp:
  enabled: false
  image: quay.io/cgrepo/centos-tools
  NetworkResourceName: intel.com/sriov_netdevice
  # if vlan is not required. keep value empty
  vlan: 100
  subnet: 192.168.100.0/24
  startip: 192.168.100.10
  endip: 192.168.100.50
  gateway: 192.168.100.1

dpdkapp:
  enabled: false
  NetworkResourceName: intel.com/dpdk_netdevice
  image: quay.io/cgrepo/dpdk-apps:21.02
  # if vlan is not required. keep value empty
  vlan: 100
  windriverisolcpus: false

cpupinapp:
  enabled: false
  image: quay.io/cgrepo/centos-tools
  cpucount: 1
  windriverisolcpus: false

hugepageapp:
  enabled: false
  image: quay.io/cgrepo/centos-tools
  cpucount: 1
  hugepages: 1Gi

dbapp:
  enabled: false
  feimage: quay.io/cgrepo/adminer:4.7
  dbimage: quay.io/cgrepo/mysql:5.6
  nodePort: 31000
  dbPassword: something
  storageClass: vsphere-sc
  fereplicas: 1

multinetapp:
  enabled: false
  image: quay.io/cgrepo/centos-tools
  subnet: 192.167.7.0/24
  startip: 192.167.7.20
  endip: 192.167.7.100
  gateway: 192.167.7.1
