apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-svc
  labels:
    app: {{ .Release.Name }}-dbapp
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-dbapp
    layer: backend
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  ports:
    - name: mysql
      port: 3306
