apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fe-dep
  labels:
    app: {{ .Release.Name }}-dbapp
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.fereplicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-dbapp
        layer: frontend
        chart: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: webserver
          image: {{ .Values.feimage }}
          env:
            - name: ADMINER_DEFAULT_SERVER
              value: {{ .Release.Name }}-db-svc
  selector:
    matchLabels:
      app: {{ .Release.Name }}-dbapp
      layer: frontend
      chart: {{ .Chart.Name }}
      release: {{ .Release.Name }}
