apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fe-svc
  labels:
    app: {{ .Release.Name }}-dbapp
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-dbapp
    layer: frontend
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  ports:
    - name: adminer
      port: 8080
      nodePort: {{ .Values.nodePort }}
